### ISSUE TITLE
Small Readme enhancement for code-workspace file

### ISSUE THREAD

**Issue by TonyGravagno** [coozieki/php-implementor#4]
As I was thinking about setting autoload paths for this extension it occurred to me that we must not put the php-implementor settings in the VSCode User settings.json - they belong in the .code-workspace settings.

OK, maybe it's just my own silly lack of foresight, but perhaps you can update the Readme to indicate that this is where all such changes need to be made.

Thanks

**Comment by coozieki** [comment]
Yes, there is a .vscode/settings.json file where you can define your workspace related settings. That will be a good enhancement for readme. Thanks

**Comment by coozieki** [comment]
Closed by 0f5ddba052cabf6d936e1f289deda0c0706b03f6.

Also added info about composer autoloads
