### ISSUE TITLE
Comment on class declaration line confuses extension

### ISSUE THREAD

**Issue by TonyGravagno** [coozieki/php-implementor#5]
Consider:

`class Foo implements IDoSomething // comment { }`

The extension attempts to open a file like "IDoSomething/comment.php", which of course doesn't exist.

While PHPDoc comments should be above that line, it's not invalid to have a comment like this. I found this because I had temporarily commented out an 'extends' clause:

From `class Foo extends Bar implements IDoSomething { }`  
To  `class Foo implements IDoSomething // extends Bar { }`

I believe you're looking for the word `implements` scanning for the next brace '{' or the EOL, and parsing any interfaces `IFirst, ISecond, IThird`. To handle a comment perhaps you can further trim anything after the last "comma [space] word". I believe that's easier than scanning for comments which may begin with `//`, `/*`, or `#`.

Thanks.

**Comment by coozieki** [comment]
Fixed by c8d6dd30ecac84e1cd125217fa6f55e4e71f9589

Tested on this file if you're interested :)

```php
<?php

namespace App;

use App\Parents\ParentInterface /* strange comment */ as AsParentInterface;
use App\Parents;

/*
123
*/
# 221312
class MyClass //comment3
# 221312
extends namespace\Parents\Parent3 # 221312
  //comment1  
  /*asdasdas*/
              implements AsParentInterface, Parents\ParentInterface2, /** dasdasd */ \App\Parents\ParentInterface3, ParentInterface4 // comment2
{
  # 221312
}
# 221312
```
